# SPDX-FileCopyrightText: 2024-2026 Wissem Chiha
# SPDX-License-Identifier: MIT

load("@rules_cc//cc:cc_test.bzl", "cc_test")

filegroup(
    name = "assets",
    srcs = glob(["assets/**"]),
    visibility = ["//visibility:public"],
)

cc_test(
    name = "camera_test",
    srcs = ["camera_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "geometry_parser_test",
    srcs = ["geometry_parser_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "inertia_parser_test",
    srcs = ["inertia_parser_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "internal_graph_test",
    srcs = ["internal_graph_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "version_test",
    srcs = ["version_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "pose_test",
    srcs = ["pose_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "color_test",
    srcs = ["color_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "joint_test",
    srcs = ["joint_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "mesh_test",
    srcs = ["mesh_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "link_test",
    srcs = ["link_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "pose_parser_test",
    srcs = ["pose_parser_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "property_parser_test",
    srcs = ["property_parser_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "visual_parser_test",
    srcs = ["visual_parser_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "collision_parser_test",
    srcs = ["collision_parser_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "link_parser_test",
    srcs = ["link_parser_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "joint_parser_test",
    srcs = ["joint_parser_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "string_utils_test",
    srcs = ["string_utils_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "model_test",
    srcs = ["model_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "model_parser_test",
    srcs = ["model_parser_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

cc_test(
    name = "material_parser_test",
    srcs = ["material_parser_test.cc"],
    deps = [
        "//:urdf",
        "@gtest//:gtest_main",
    ],
    data = ["//test:assets"],
)

