sonar.projectKey=wissem01chiha_liburdf
sonar.organization=wissem01chiha

sonar.projectName=liburdf
sonar.projectVersion=0.1.1

# Path is relative to the sonar-project.properties file.
# Replace "\" by "/" on Windows.
sonar.sources= src,include,test, python, cmake

sonar.sourceEncoding=UTF-8