# SPDX-FileCopyrightText: 2024-2026 Wissem Chiha
# SPDX-License-Identifier: MIT

if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    if (CMAKE_BUILD_TYPE STREQUAL "Debug")
        list(APPEND urdf_cflags "-O0" "-g" "-DDEBUG")
    elseif (CMAKE_BUILD_TYPE STREQUAL "Release")
        list(APPEND urdf_cflags "-O3")
    endif()
    list(APPEND urdf_test_cflags -g -DDEBUG)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
        list(APPEND urdf_cflags "/Od" "/Zi" "/DDEBUG")
    elseif (CMAKE_BUILD_TYPE STREQUAL "Release")
        list(APPEND urdf_cflags "/O2")
    endif()
    list(APPEND urdf_test_cflags /Zi /DDEBUG)
    list(APPEND urdf_test_cflags /DEBUG)
endif()

if(LIBURDF_ENABLE_TESTING_COVERAGE)
  if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    add_compile_options(--coverage)
    add_link_options(--coverage)
  endif ()
endif ()

if(LIBURDF_ENABLE_SANITIZERS)
    if(WIN32)
        warning("Sanitizers are not supported on windows")
    else()
        if(LIBURDF_ENABLE_ASAN) 
            list(APPEND urdf_cflags "-fsanitize=address")
            list(APPEND urdf_test_cflags "-fsanitize=address")
            list(APPEND urdf_link_cflags "-fsanitize=address")
        endif()
        if(LIBURDF_ENABLE_UBSAN)
            list(APPEND urdf_cflags "-fsanitize=undefined")
            list(APPEND urdf_test_cflags "-fsanitize=undefined")
            list(APPEND urdf_link_cflags "-fsanitize=undefined")
        endif()
        if(LIBURDF_ENABLE_MSAN)
            if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
                list(APPEND urdf_cflags "-fsanitize=memory")
                list(APPEND urdf_test_cflags "-fsanitize=memory")
                list(APPEND urdf_link_cflags "-fsanitize=memory")
            endif()
        endif()
    endif()
endif()